### PR TITLE
feat(core): support SSR by not loading bodymovin on server and return an empty component

### LINKED ISSUE #9: add universal "support" (serverside rendering)
When you use react-bodymovin in a universal react app with serverside rendering, the app will currently crash. This is related to https://github.com/bodymovin/bodymovin/issues/440.

I think it would be good to catch this already in `react-bodymovin`, because I'm pretty sure the react component would break if this switch is included in `bodymovin`. By catching it you can just return an empty component, which will not break the whole app.

### PR DESCRIPTION
**Pull request by acidicX**
closes #9

### CODE REVIEW

**Comment by Olical** [comment]
Oh, I've just realised I don't have write access now, I'm afraid you'll need to get someone else to merge this. Sadly I was the creator / maintainer of this, so I wouldn't expect anyone at Qubit to be too interested in sorting this out. @lozlow maybe you can hit merge or prod someone? Or give me the repo? ¯\_(ツ)_/¯

**Comment by fabien0102** [comment]
Any news? I really need this feature 😉

**Comment by ricky-scale** [comment]
I'm getting this error 
```Error in /Users/rickyrauch/Sites/scaleapi.com/frontend/pages/index.js?entry Module not found: Error: Can't resolve 'react-bodymovin' in '/Users/rickyrauch/Sites/scaleapi.com/frontend/pages'```

I'm using Next.js

**Comment by acidicX** [comment]
@ricky-scale not sure what this has to do with this PR? can you elaborate?

**Comment by acidicX** [comment]
@Olical ping :)

**Comment by Olical** [comment]
I don't have access I'm afraid since I no longer work at Qubit 😢

Maybe the best bet would be to fork it and re-publish it with this fix?

**Comment by acidicX** [comment]
I'm not sure I have the time to maintain it right now, but it's not really a large component. Might be the best way to go though.

**Comment by acidicX** [comment]
@Olical do you still have access to the NPM account? So we could at least re-use the package name

**Comment by Olical** [comment]
Yes, I do, it's published under my account. Would like to be sure Qubit is okay with that though. @emreb, any thoughts? 😄

**Comment by Olical** [comment]
Merged into https://github.com/Olical/react-bodymovin - feel free to close, I can not edit this repository anymore.

**Pull request closed without merging**
